const state = { ws: null, id: null, pc: null, screen: null, controlChannel: null, controlAllowed: false, qualityMode: 'auto', pingSamples: [], jitter: 0, uploadMbps: 0 };
function wsUrl() { const p = location.protocol === 'https:' ? 'wss' : 'ws'; return `${p}://${location.host}/ws`; }
function connectWs() { state.ws = new WebSocket(wsUrl()); state.ws.onmessage = onWsMessage; state.ws.onopen = () => join(); }
function sendWs(obj) { if (state.ws && state.ws.readyState === WebSocket.OPEN) state.ws.send(JSON.stringify(obj)); }
function join() { const name = document.getElementById('name').value || 'Cliente'; const browser = navigator.userAgent; const os = navigator.platform || ''; sendWs({ type: 'join', role: 'client', name, browser, os }); }
function onWsMessage(ev) { const msg = JSON.parse(ev.data); if (msg.type === 'joined') { state.id = msg.id; runNetTests(); } else if (msg.type === 'offer') { handleOffer(msg); } else if (msg.type === 'candidate') { handleCandidate(msg); } else if (msg.type === 'request_control') { state.controlAllowed = false; document.getElementById('allow').disabled = false; } else if (msg.type === 'set_quality') { state.qualityMode = msg.mode; if (state.screen) adjustSenderQuality(); } else if (msg.type === 'pong') { const now = performance.now(); const rtt = now - msg.ts; state.pingSamples.push(rtt); if (state.pingSamples.length > 20) state.pingSamples.shift(); computeJitter(); netRender(); sendWs({ type: 'netupdate', ping: avg(state.pingSamples) }); } else if (msg.type === 'upload_ack') { const dt = (performance.now() - msg.ts) / 1000; const mbps = (msg.size * 8) / 1000000 / dt; state.uploadMbps = mbps; netRender(); if (state.qualityMode === 'auto' && state.screen) adjustSenderQuality(); } }
function avg(a) { return a.reduce((s, v) => s + v, 0) / (a.length || 1); }
function computeJitter() { const m = avg(state.pingSamples); const dev = Math.sqrt(avg(state.pingSamples.map((v) => (v - m) * (v - m)))); state.jitter = dev; }
function pingLoop() { const ts = performance.now(); sendWs({ type: 'ping', ts }); }
function uploadProbe() { const size = 2 * 1024 * 1024; const buf = new Uint8Array(size); sendWs({ type: 'upload_probe', size, ts: performance.now() }); }
function runNetTests() { setInterval(pingLoop, 2000); setTimeout(uploadProbe, 1500); }
function chooseQuality() { const mbps = state.uploadMbps; if (state.qualityMode === 'low') return { w: 640, h: 360, f: 15 }; if (state.qualityMode === 'high') return { w: 1920, h: 1080, f: 30 }; if (mbps > 15) return { w: 1920, h: 1080, f: 30 }; if (mbps > 5) return { w: 1280, h: 720, f: 30 }; if (mbps > 1) return { w: 854, h: 480, f: 24 }; return { w: 640, h: 360, f: 15 }; }
async function shareScreen() { const q = chooseQuality(); const stream = await navigator.mediaDevices.getDisplayMedia({ video: { width: q.w, height: q.h, frameRate: q.f }, audio: false }); state.screen = stream; document.getElementById('preview').srcObject = stream; await ensurePc(); stream.getTracks().forEach((t) => state.pc.addTrack(t, stream)); }
async function ensurePc() { if (state.pc) return; state.pc = new RTCPeerConnection({ iceServers: [{ urls: 'stun:stun.l.google.com:19302' }, { urls: 'turn:localhost:3478', username: 'webrtc', credential: '12345' }] }); state.pc.addEventListener('icecandidate', (e) => { if (e.candidate) sendWs({ type: 'candidate', to: state.peerTech, toRole: 'tech', candidate: e.candidate }); }); state.pc.addEventListener('datachannel', (e) => { state.controlChannel = e.channel; state.controlChannel.onmessage = onControlMessage; }); }
function onControlMessage(ev) { const cmd = JSON.parse(ev.data); if (cmd.type === 'mouse' && state.controlAllowed) { } if (cmd.type === 'key' && state.controlAllowed) { } }
function adjustSenderQuality() { const senders = state.pc.getSenders().filter((s) => s.track && s.track.kind === 'video'); const q = chooseQuality(); senders.forEach((s) => s.setParameters({ encodings: [{ maxBitrate: 2500000 }] })); }
async function handleOffer(msg) { state.peerTech = msg.from; await ensurePc(); await state.pc.setRemoteDescription({ type: 'offer', sdp: msg.sdp }); const ans = await state.pc.createAnswer(); await state.pc.setLocalDescription(ans); sendWs({ type: 'answer', to: msg.from, sdp: ans.sdp }); }
function handleCandidate(msg) { state.pc && state.pc.addIceCandidate(msg.candidate); }
function allowControl() { state.controlAllowed = true; document.getElementById('allow').disabled = true; if (!state.controlChannel) return; document.addEventListener('mousemove', (e) => state.controlChannel.send(JSON.stringify({ type: 'mouse', x: e.clientX, y: e.clientY, b: 0 }))); document.addEventListener('mousedown', (e) => state.controlChannel.send(JSON.stringify({ type: 'mouse', x: e.clientX, y: e.clientY, b: 1 }))); document.addEventListener('mouseup', (e) => state.controlChannel.send(JSON.stringify({ type: 'mouse', x: e.clientX, y: e.clientY, b: 2 }))); document.addEventListener('keydown', (e) => state.controlChannel.send(JSON.stringify({ type: 'key', k: e.key }))); }
function netRender() { const el = document.getElementById('net'); el.textContent = `ping ${Math.round(avg(state.pingSamples))} ms | jitter ${Math.round(state.jitter)} ms | upload ${state.uploadMbps.toFixed(2)} Mbps | modo ${state.qualityMode}`; }
document.getElementById('start').onclick = connectWs;
document.getElementById('share').onclick = shareScreen;
document.getElementById('allow').onclick = allowControl;
document.getElementById('allow').disabled = true;